"""Initial Migration

Revision ID: c332bf374a50
Revises: d559cffc18de
Create Date: 2019-12-02 16:32:04.046725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c332bf374a50'
down_revision = 'd559cffc18de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'title')
    # ### end Alembic commands ###
